### PR TITLE
anywidget v0.1.1

### PR DESCRIPTION
**Pull request by manzt**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by manzt** [comment]
hi @giswqs, I made a release earlier today and forget that I needed to update the packaging here so #5  is failing. Is it possible to apply changes to that open PR instead of here?

**Comment by giswqs** [comment]
@manzt If the autobot fails, then we need to manually submit a PR. I can help you on this PR. 

You need to update the sha256 to `f9501dfc7aabc1f6ee8ddc9feafe85bae4e9418d8c17485666cdd556322e9176`

**Comment by manzt** [comment]
Thanks for the help! :) 

> You need to update the sha256 to `f9501dfc7aabc1f6ee8ddc9feafe85bae4e9418d8c17485666cdd556322e9176`

The `sha256` in `meta.yaml`? If so, that is the current sha256 listed there. Sorry, my first time working with conda feedstocks...

**Comment by giswqs** [comment]
Sorry, I copied the old one. It should be `bef4d20751f7e14fcc7a90c0b2798bd836068b25104ad5f0312586da82ddde20`

It can be retrieved using `openssl sha256 filename.tar.gz`

**Comment by manzt** [comment]
woo, thanks for the help! 🚀

**Pull request merged**
